services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: RidaDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d RidaDb"]
      interval: 5s
      timeout: 5s
      retries: 5

  rida.api:
    container_name: rida.api
    build:
      context: .
      dockerfile: src/App.Api/Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=123;Host=postgres;Port=5432;Database=RidaDb;
    ports:
      - "8080:8080"

volumes:
  postgres_data: